name: device_info_windows
description: A plugin that uses FFI to offer device information
version: 0.2.0-nullsafety.0
homepage: https://github.com/timsneath/device_info_windows

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  ffi: ^0.2.0-nullsafety.1
  flutter:
    sdk: flutter
  win32: ^2.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.1

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: DeviceInfoWindows