name: device_info_windows
description: Uses WMI to read information about running processes from the underlying Windows operating system.
version: 1.0.0
homepage: https://github.com/timsneath/device_info_windows

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  flutter:
    sdk: flutter
  win32: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: DeviceInfoWindows