name: device_info_windows
description: A plugin that uses FFI to offer device information
version: 0.0.2
homepage: https://github.com/timsneath/device_info_windows

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  win32: ^1.5.0
  # win32:
  #   path:
  #     ../win32
  ffi: ^0.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      windows:
        dartPluginClass: DeviceInfoWindows